In [5]:
#!pip install pandas

In [6]:
# importing required modules
import numpy as np
import pandas as pd

In [7]:
# versions
print(np.__version__)
print(pd.__version__)

2.3.2
2.3.1


In [8]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
# creating empty series
s = pd.Series()
print(s)
print(len(s), type(s), id(s))

Series([], dtype: object)
0 <class 'pandas.core.series.Series'> 2725143946064


In [10]:
# creating series from ndarray
arr_data = np.array(['apple','banana','guava','pineapple'])
print(arr_data, type(arr_data))
s = pd.Series(data = arr_data)
print(s)
print(type(s))
print(s[0], s[3], s[2])  # indexing
print(s[:2])  # slicing
print(s[2:])  # slicing

['apple' 'banana' 'guava' 'pineapple'] <class 'numpy.ndarray'>
0        apple
1       banana
2        guava
3    pineapple
dtype: object
<class 'pandas.core.series.Series'>
apple pineapple guava
0     apple
1    banana
dtype: object
2        guava
3    pineapple
dtype: object


In [11]:
arr_data = np.array([100, 300, 200, 500, 400])
print(arr_data, type(arr_data))
s = pd.Series(data = arr_data, copy=False)
print(s)
print(type(s))
s[2] = 888
arr_data[0] = 999
print(arr_data, type(arr_data))
print(s)

[100 300 200 500 400] <class 'numpy.ndarray'>
0    100
1    300
2    200
3    500
4    400
dtype: int64
<class 'pandas.core.series.Series'>
[999 300 888 500 400] <class 'numpy.ndarray'>
0    999
1    300
2    888
3    500
4    400
dtype: int64


In [12]:
arr_data = np.array([100, 300, 200, 500, 400])
print(arr_data, type(arr_data))
s = pd.Series(data = arr_data, copy=True)
print(s)
print(type(s))
s[2] = 888
arr_data[0] = 999
print(arr_data, type(arr_data))
print(s)

[100 300 200 500 400] <class 'numpy.ndarray'>
0    100
1    300
2    200
3    500
4    400
dtype: int64
<class 'pandas.core.series.Series'>
[999 300 200 500 400] <class 'numpy.ndarray'>
0    100
1    300
2    888
3    500
4    400
dtype: int64


In [13]:
arr_data = np.array(['apple','banana','guava','pineapple'])
print(arr_data, type(arr_data))
s = pd.Series(data = arr_data, index = [101, 102, 103, 104])
print(s)
print(type(s))
print(s[102])

['apple' 'banana' 'guava' 'pineapple'] <class 'numpy.ndarray'>
101        apple
102       banana
103        guava
104    pineapple
dtype: object
<class 'pandas.core.series.Series'>
banana


In [14]:
arr_data = np.array(['apple','banana','guava','pineapple'])
print(arr_data, type(arr_data))
s = pd.Series(data = arr_data, index = [101, 103, 101, 103])
print(s)
print(type(s))
print(s[101])
print(s[103])

['apple' 'banana' 'guava' 'pineapple'] <class 'numpy.ndarray'>
101        apple
103       banana
101        guava
103    pineapple
dtype: object
<class 'pandas.core.series.Series'>
101    apple
101    guava
dtype: object
103       banana
103    pineapple
dtype: object


In [15]:
arr_data = np.array(['apple','banana','guava','pineapple'])
print(arr_data, type(arr_data))
s = pd.Series(data = arr_data, index = ['fruits-1','fruits-2','fruits-3','fruits-2'])
print(s)
print(type(s))
print(s['fruits-1'], s[0])
print(s['fruits-3'], s[2])
print(s['fruits-2'])


['apple' 'banana' 'guava' 'pineapple'] <class 'numpy.ndarray'>
fruits-1        apple
fruits-2       banana
fruits-3        guava
fruits-2    pineapple
dtype: object
<class 'pandas.core.series.Series'>
apple apple
guava guava
fruits-2       banana
fruits-2    pineapple
dtype: object


In [16]:
# creating series from a dictionary
dict_data = {'apple':100, 'banana':250, 'orange':750, 'lime':550}
print(dict_data, type(dict_data))
s = pd.Series(data=dict_data)
print(s)
print(type(s))

{'apple': 100, 'banana': 250, 'orange': 750, 'lime': 550} <class 'dict'>
apple     100
banana    250
orange    750
lime      550
dtype: int64
<class 'pandas.core.series.Series'>


In [17]:
dict_data = {'apple':100, 'banana':250, 'orange':750, 'lime':550}
print(dict_data, type(dict_data))
s = pd.Series(data=dict_data, index = ['apple','lime','orange','banana','banana','lemon'])
print(s)
print(type(s))
print(s[0], s['apple'])
print(s[:3])

{'apple': 100, 'banana': 250, 'orange': 750, 'lime': 550} <class 'dict'>
apple     100.0
lime      550.0
orange    750.0
banana    250.0
banana    250.0
lemon       NaN
dtype: float64
<class 'pandas.core.series.Series'>
100.0 100.0
apple     100.0
lime      550.0
orange    750.0
dtype: float64


In [18]:
# create Series from a scalar
s = pd.Series(5, index = [0, 1, 2, 3, 4, 5])
print(s)

0    5
1    5
2    5
3    5
4    5
5    5
dtype: int64


In [19]:
s = pd.Series(5, index = range(0, 6, 2))
print(s)

0    5
2    5
4    5
dtype: int64


In [20]:
# creating Series from a list
list_data = [101, 202, 404, 303, 505]
print(list_data, type(list_data))
s = pd.Series(data=list_data, index=['red','green','brown','blue','magenta'])
print(s)
print(s[0], s['red'], s[4], s['magenta'])  # indexing
print(s[-1], s['magenta'])  # indexing
print(s[2:])  # slicing (2nd inde onwards)
print(s[:-1])  # slicing (from first index till the last but one)

[101, 202, 404, 303, 505] <class 'list'>
red        101
green      202
brown      404
blue       303
magenta    505
dtype: int64
101 101 505 505
505 505
brown      404
blue       303
magenta    505
dtype: int64
red      101
green    202
brown    404
blue     303
dtype: int64


In [21]:
print(s)
print(s.sort_index())
print(s.sort_values())
print(s.argmin(), s.argmax(), len(s), s.count(), s.mean(), s.var(), s.std(), s.max(), s.min(), s.sum())

red        101
green      202
brown      404
blue       303
magenta    505
dtype: int64
blue       303
brown      404
green      202
magenta    505
red        101
dtype: int64
red        101
green      202
blue       303
brown      404
magenta    505
dtype: int64
0 4 5 5 303.0 25502.5 159.69502183850315 505 101 1515


In [22]:
import pandas as pd
import numpy as np

In [23]:
user_data = [['alice',19,'F','student'],['john',26,'M','student']]
user_columns = ['name','age','gender','job']
user1 = pd.DataFrame(data=user_data, columns=user_columns)
user1

name  age gender      job
0  alice   19      F  student
1   john   26      M  student

In [24]:
user_data = dict(name=['eric','julie'], age=[22,58], gender=['M','F'], job=['student','manager'])
print(user_data, type(user_data))
user2 = pd.DataFrame(data=user_data)
user2

{'name': ['eric', 'julie'], 'age': [22, 58], 'gender': ['M', 'F'], 'job': ['student', 'manager']} <class 'dict'>


name  age gender      job
0   eric   22      M  student
1  julie   58      F  manager

In [25]:
user_data = {'name':['peter','paul'], 'age':[33,44], 'gender':['M','F'], 'job':['engineer','scientist']}
print(user_data, type(user_data))
user3 = pd.DataFrame(data=user_data)
user3

{'name': ['peter', 'paul'], 'age': [33, 44], 'gender': ['M', 'F'], 'job': ['engineer', 'scientist']} <class 'dict'>


name  age gender        job
0  peter   33      M   engineer
1   paul   44      F  scientist

In [26]:
users = pd.concat([user1,user2,user3], ignore_index=True)
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3  julie   58      F    manager
4  peter   33      M   engineer
5   paul   44      F  scientist

In [27]:
arr_data = np.array(users)
print(arr_data, type(arr_data))
arr_data = users.to_numpy()
print(arr_data, type(arr_data))

[['alice' 19 'F' 'student']
 ['john' 26 'M' 'student']
 ['eric' 22 'M' 'student']
 ['julie' 58 'F' 'manager']
 ['peter' 33 'M' 'engineer']
 ['paul' 44 'F' 'scientist']] <class 'numpy.ndarray'>
[['alice' 19 'F' 'student']
 ['john' 26 'M' 'student']
 ['eric' 22 'M' 'student']
 ['julie' 58 'F' 'manager']
 ['peter' 33 'M' 'engineer']
 ['paul' 44 'F' 'scientist']] <class 'numpy.ndarray'>


In [28]:
dict_data = dict(name=['alice','john','eric','julie','andrew'],height=[165,180,175,180,185])
user4 = pd.DataFrame(data=dict_data)
user4

name  height
0   alice     165
1    john     180
2    eric     175
3   julie     180
4  andrew     185

In [29]:
merge_inner = pd.merge(users, user4, on='name', how='inner')
merge_inner

name  age gender      job  height
0  alice   19      F  student     165
1   john   26      M  student     180
2   eric   22      M  student     175
3  julie   58      F  manager     180

In [30]:
merge_outer = pd.merge(users, user4, on='name', how='outer')
merge_outer

name   age gender        job  height
0   alice  19.0      F    student   165.0
1  andrew   NaN    NaN        NaN   185.0
2    eric  22.0      M    student   175.0
3    john  26.0      M    student   180.0
4   julie  58.0      F    manager   180.0
5    paul  44.0      F  scientist     NaN
6   peter  33.0      M   engineer     NaN

In [31]:
merge_left = pd.merge(users, user4, on='name', how='left')
merge_left

name  age gender        job  height
0  alice   19      F    student   165.0
1   john   26      M    student   180.0
2   eric   22      M    student   175.0
3  julie   58      F    manager   180.0
4  peter   33      M   engineer     NaN
5   paul   44      F  scientist     NaN

In [32]:
merge_right = pd.merge(users, user4, on='name', how='right')
merge_right

name   age gender      job  height
0   alice  19.0      F  student     165
1    john  26.0      M  student     180
2    eric  22.0      M  student     175
3   julie  58.0      F  manager     180
4  andrew   NaN    NaN      NaN     185

In [33]:
print(type(users))
print(users.shape, users.size, len(users))
print(f"No. of rows = {users.shape[0]} and cols = {users.shape[1]}")
print(users.dtypes)

<class 'pandas.core.frame.DataFrame'>
(6, 4) 24 6
No. of rows = 6 and cols = 4
name      object
age        int64
gender    object
job       object
dtype: object


In [34]:
print(users.values, type(users.values))
print(users.index, users.shape, users.ndim)

[['alice' 19 'F' 'student']
 ['john' 26 'M' 'student']
 ['eric' 22 'M' 'student']
 ['julie' 58 'F' 'manager']
 ['peter' 33 'M' 'engineer']
 ['paul' 44 'F' 'scientist']] <class 'numpy.ndarray'>
RangeIndex(start=0, stop=6, step=1) (6, 4) 2


In [35]:
users.head(3)

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student

In [36]:
users.tail(3)

name  age gender        job
3  julie   58      F    manager
4  peter   33      M   engineer
5   paul   44      F  scientist

In [37]:
users.sample(2)

name  age gender        job
4  peter   33      M   engineer
5   paul   44      F  scientist

In [38]:
print(users.index)
print(users.columns)
print(users.any())

RangeIndex(start=0, stop=6, step=1)
Index(['name', 'age', 'gender', 'job'], dtype='object')
name      True
age       True
gender    True
job       True
dtype: bool


In [39]:
print(users.gender)
print(users.gender.value_counts())

0    F
1    M
2    M
3    F
4    M
5    F
Name: gender, dtype: object
gender
F    3
M    3
Name: count, dtype: int64


In [40]:
print(users.job)
print(users.job.value_counts())

0      student
1      student
2      student
3      manager
4     engineer
5    scientist
Name: job, dtype: object
job
student      3
manager      1
engineer     1
scientist    1
Name: count, dtype: int64


In [41]:
users.describe()

age
count   6.000000
mean   33.666667
std    14.895189
min    19.000000
25%    23.000000
50%    29.500000
75%    41.250000
max    58.000000

In [42]:
users.describe(include = 'object')

name gender      job
count       6      6        6
unique      6      2        4
top     alice      F  student
freq        1      3        3

In [43]:
users.describe(include = 'all')

name        age gender      job
count       6   6.000000      6        6
unique      6        NaN      2        4
top     alice        NaN      F  student
freq        1        NaN      3        3
mean      NaN  33.666667    NaN      NaN
std       NaN  14.895189    NaN      NaN
min       NaN  19.000000    NaN      NaN
25%       NaN  23.000000    NaN      NaN
50%       NaN  29.500000    NaN      NaN
75%       NaN  41.250000    NaN      NaN
max       NaN  58.000000    NaN      NaN

In [44]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    6 non-null      object
 1   age     6 non-null      int64 
 2   gender  6 non-null      object
 3   job     6 non-null      object
dtypes: int64(1), object(3)
memory usage: 324.0+ bytes


In [45]:
# users.describe(include = 'all').transpose()
users.describe(include = 'all').T

count unique      top freq       mean        std   min   25%   50%  \
name       6      6    alice    1        NaN        NaN   NaN   NaN   NaN   
age      6.0    NaN      NaN  NaN  33.666667  14.895189  19.0  23.0  29.5   
gender     6      2        F    3        NaN        NaN   NaN   NaN   NaN   
job        6      4  student    3        NaN        NaN   NaN   NaN   NaN   

          75%   max  
name      NaN   NaN  
age     41.25  58.0  
gender    NaN   NaN  
job       NaN   NaN

In [46]:
print(users.age)
print(users['age'])


0    19
1    26
2    22
3    58
4    33
5    44
Name: age, dtype: int64
0    19
1    26
2    22
3    58
4    33
5    44
Name: age, dtype: int64


In [47]:
print(users[['age','name']])
my_columns = ['age', 'name', 'job']
print(users[my_columns])

   age   name
0   19  alice
1   26   john
2   22   eric
3   58  julie
4   33  peter
5   44   paul
   age   name        job
0   19  alice    student
1   26   john    student
2   22   eric    student
3   58  julie    manager
4   33  peter   engineer
5   44   paul  scientist


In [48]:
df = users.copy()
print(df.iloc[4], type(df.iloc[4]))
print(df.loc[4], type(df.loc[4]))

name         peter
age             33
gender           M
job       engineer
Name: 4, dtype: object <class 'pandas.core.series.Series'>
name         peter
age             33
gender           M
job       engineer
Name: 4, dtype: object <class 'pandas.core.series.Series'>


In [49]:
print(df.iloc[4][3], df.iloc[4]['job'], df.loc[4][3], df.loc[4]['job'])
print(df.iloc[4, 3], df.iloc[4]['job'], df.loc[4][3], df.loc[4, 'job'])

engineer engineer engineer engineer
engineer engineer engineer engineer


In [50]:
# Class Assignment - 1
# Increase all the ages with value 100
df = users.copy()
df.age = df.age + 100
print(df)
df.iloc[:, 1] += 100
print(df)

    name  age gender        job
0  alice  119      F    student
1   john  126      M    student
2   eric  122      M    student
3  julie  158      F    manager
4  peter  133      M   engineer
5   paul  144      F  scientist
    name  age gender        job
0  alice  219      F    student
1   john  226      M    student
2   eric  222      M    student
3  julie  258      F    manager
4  peter  233      M   engineer
5   paul  244      F  scientist


In [51]:
# Class Assignment - 2
# Replace all the names in upper case ('john' -> 'JOHN') 
# and all the job in proper case ('student' -> 'Student'). 
df.sample()

name  age gender      job
2  eric  222      M  student

In [52]:
df = users.copy()
df.loc[:, 'name'] = df.loc[:, 'name'].str.upper()
df.loc[:, 'job'] = df.loc[:, 'job'].str.title()
print(df)

    name  age gender        job
0  ALICE   19      F    Student
1   JOHN   26      M    Student
2   ERIC   22      M    Student
3  JULIE   58      F    Manager
4  PETER   33      M   Engineer
5   PAUL   44      F  Scientist


In [53]:
df = users.copy()
df.name = df.name.str.upper()
df.job = df.job.str.title()
print(df)

    name  age gender        job
0  ALICE   19      F    Student
1   JOHN   26      M    Student
2   ERIC   22      M    Student
3  JULIE   58      F    Manager
4  PETER   33      M   Engineer
5   PAUL   44      F  Scientist


In [54]:
df = users.copy()
print(df.age <= 40)
print(df[df.age <= 40])
print(df[~(df.age <= 40)])  # ~ => not

0     True
1     True
2     True
3    False
4     True
5    False
Name: age, dtype: bool
    name  age gender       job
0  alice   19      F   student
1   john   26      M   student
2   eric   22      M   student
4  peter   33      M  engineer
    name  age gender        job
3  julie   58      F    manager
5   paul   44      F  scientist


In [55]:
# Class Assignment - 2
# Display name, age and gender where gender is 'F' and age <= 40.
# select name, age, gender from df
# where age <= 40 and gender = 'F';
df[(df.age <= 40) & (df.gender == 'F')][['name','age','gender']]

name  age gender
0  alice   19      F

In [56]:
# Query: Find those person details who is male and age greater
# than 30 or female and age less than 40.
df = users.copy()
df[((df.gender == 'M') & (df.age > 30)) | ((df.gender == 'F') & (df.age < 40))].name

0    alice
4    peter
Name: name, dtype: object

In [57]:
# Query: Print those names who are having job either
# 'student' or 'engineer'
print(df.job.isin(['student', 'engineer']))
df[df.job.isin(['student', 'engineer'])].name

0     True
1     True
2     True
3    False
4     True
5    False
Name: job, dtype: bool


0    alice
1     john
2     eric
4    peter
Name: name, dtype: object

In [58]:
df = users.copy()
print(df.job.sort_values())
print(df.age.sort_values())

4     engineer
3      manager
5    scientist
0      student
1      student
2      student
Name: job, dtype: object
0    19
2    22
1    26
4    33
5    44
3    58
Name: age, dtype: int64


In [59]:
df = users.copy()
print(df.job.sort_values(ascending = False))
print(df.age.sort_values(ascending = False))

0      student
1      student
2      student
5    scientist
3      manager
4     engineer
Name: job, dtype: object
3    58
5    44
4    33
1    26
2    22
0    19
Name: age, dtype: int64


In [60]:
df = users.copy()
df.sort_values(by='job', ascending=True, inplace=True)
# df = df.sort_values(by='job', ascending=True)
df.index = range(0, len(df))
df

name  age gender        job
0  peter   33      M   engineer
1  julie   58      F    manager
2   paul   44      F  scientist
3  alice   19      F    student
4   john   26      M    student
5   eric   22      M    student