In [2]:
# importing required modules
#!pip install numpy
import numpy as np
print(np.__version__)

2.3.2


In [3]:
# create nd-array from a list
data1 = [11, 22, 33, 44, 55, 66, 77, 88]
print(data1, len(data1), type(data1))
arr1 = np.array(data1)
print(arr1, len(arr1), type(arr1), arr1.dtype)

[11, 22, 33, 44, 55, 66, 77, 88] 8 <class 'list'>
[11 22 33 44 55 66 77 88] 8 <class 'numpy.ndarray'> int64


In [4]:
# create nd-array from a list
data1 = [11, 22, 33, 44.5, 55, 66, 77, 88]
print(data1, len(data1), type(data1))
arr1 = np.array(data1)
print(arr1, len(arr1), type(arr1), arr1.dtype)

[11, 22, 33, 44.5, 55, 66, 77, 88] 8 <class 'list'>
[11.  22.  33.  44.5 55.  66.  77.  88. ] 8 <class 'numpy.ndarray'> float64


In [5]:
# create nd-array from a list
data1 = [11, 22, 33, 44, 55, 66, 77, 88, True, False]
print(data1, len(data1), type(data1))
arr1 = np.array(data1)
print(arr1, len(arr1), type(arr1), arr1.dtype)

[11, 22, 33, 44, 55, 66, 77, 88, True, False] 10 <class 'list'>
[11 22 33 44 55 66 77 88  1  0] 10 <class 'numpy.ndarray'> int64


In [6]:
# create nd-array from a list
data1 = [11, 22, 33, 44, 55, 66.5, 77, 'AEC', 88, True, False]
print(data1, len(data1), type(data1))
arr1 = np.array(data1)
print(arr1, len(arr1), type(arr1), arr1.dtype)

[11, 22, 33, 44, 55, 66.5, 77, 'AEC', 88, True, False] 11 <class 'list'>
['11' '22' '33' '44' '55' '66.5' '77' 'AEC' '88' 'True' 'False'] 11 <class 'numpy.ndarray'> <U32


In [7]:
data1 = range(1, 20, 3)   # list containing 0 to 9
print(data1)
arr1 = np.array(data1)
print(arr1)
for item in np.nditer(arr1):
    print(item, end = ", ")

range(1, 20, 3)
[ 1  4  7 10 13 16 19]
1, 4, 7, 10, 13, 16, 19, 

In [8]:
data2 = [range(1, 5), range(6, 10)]
print(data2)
arr2 = np.array(data2)
print(arr2)   # creating 2-dimensional array
for item in np.nditer(arr2):
    print(item, end = ", ")

[range(1, 5), range(6, 10)]
[[1 2 3 4]
 [6 7 8 9]]
1, 2, 3, 4, 6, 7, 8, 9, 

In [9]:
data1 = [11, 22, 33, 44]
arr1 = np.array(data1)
print(data1, arr1)
result = list(arr1)
print(arr1, result)
result = arr1.tolist()
print(arr1, result)

[11, 22, 33, 44] [11 22 33 44]
[11 22 33 44] [np.int64(11), np.int64(22), np.int64(33), np.int64(44)]
[11 22 33 44] [11, 22, 33, 44]


In [10]:
data2 = [[11, 22, 33, 44], [55, 66, 77, 88]]
arr2 = np.array(data2)
print(data2)
print(arr2)
result = list(arr2)
print(arr2)
print(result)
result = arr2.tolist()
print(arr2)
print(result)

[[11, 22, 33, 44], [55, 66, 77, 88]]
[[11 22 33 44]
 [55 66 77 88]]
[[11 22 33 44]
 [55 66 77 88]]
[array([11, 22, 33, 44]), array([55, 66, 77, 88])]
[[11 22 33 44]
 [55 66 77 88]]
[[11, 22, 33, 44], [55, 66, 77, 88]]


In [11]:
# examining arrays
arr1 = np.array([11, 22, 33, 44, 55, 66, 77, 88])
print(arr1, type(arr1), id(arr1))
print(arr1.dtype, arr1.shape, len(arr1), arr1.ndim)
print(arr1.size, arr1.nbytes)  # total number of data items

[11 22 33 44 55 66 77 88] <class 'numpy.ndarray'> 2488573177808
int64 (8,) 8 1
8 64


In [12]:
var1 = (8)
print(var1, type(var1))
var1 = (8,)  # singleton representation of a tuple
print(var1, type(var1))

8 <class 'int'>
(8,) <class 'tuple'>


In [13]:
arr2 = np.array([[11, 22, 33, 44], [55, 66, 77, 88]])
print(arr2, type(arr2), id(arr2))
print(arr2.dtype, arr2.shape, len(arr2), arr2.ndim)
print(arr2.size)  # total number of data items
print(f"Number of rows = {arr2.shape[0]} and columns = {arr2.shape[1]}")

[[11 22 33 44]
 [55 66 77 88]] <class 'numpy.ndarray'> 2488573178096
int64 (2, 4) 2 2
8
Number of rows = 2 and columns = 4


In [14]:
# create special arrays
print(np.zeros(10))
print(np.zeros(10, np.int32))
print(np.zeros(10).astype(int))
print(np.zeros((2, 5)))
print(np.zeros((2, 5), np.int32))
print(np.zeros((2, 5)).astype(int))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [15]:
print(np.ones(10))
print(np.ones(10, np.int32))
print(np.ones(10).astype(int))
print(np.ones((2, 5)))
print(np.ones((2, 5), np.int32))
print(np.ones((2, 5)).astype(int))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [16]:
print(np.zeros((3, 5)) + 5)   # vector and scalar operation
print(np.ones((3, 5)) * 5)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [17]:
print(np.linspace(1, 10, 5))
print(np.linspace(1, 50, 11))

[ 1.    3.25  5.5   7.75 10.  ]
[ 1.   5.9 10.8 15.7 20.6 25.5 30.4 35.3 40.2 45.1 50. ]


In [18]:
print(np.logspace(0, 3, 4))
print(np.logspace(0, 3, 4, base = 2))
print(np.logspace(0, 8, 9, base = 2))
print(np.logspace(0, 8, 9, base = np.e))

[   1.   10.  100. 1000.]
[1. 2. 4. 8.]
[  1.   2.   4.   8.  16.  32.  64. 128. 256.]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03]


In [19]:
arr1 = np.arange(1, 11, 2)
print(arr1, type(arr1))
arr1 = np.arange(11, 0, -2)
print(arr1, type(arr1))
arr1 = np.arange(1, 11, 2).astype(float)
print(arr1, type(arr1))

[1 3 5 7 9] <class 'numpy.ndarray'>
[11  9  7  5  3  1] <class 'numpy.ndarray'>
[1. 3. 5. 7. 9.] <class 'numpy.ndarray'>


In [20]:
# reshape of ndarray
print(np.arange(20))
print(np.arange(20).reshape(4, 5))
print(np.arange(20).reshape(4, -1))
print(np.arange(20).reshape(-1, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [21]:
print(np.arange(20).reshape(2, -1, 5))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [22]:
arr2 = np.arange(20).reshape(2, 10)
print(arr2)
arr1 = arr2.flatten()
print(arr1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [23]:
arr2 = np.arange(20).reshape(2, 2, 5)
print(arr2)
arr1 = arr2.flatten()
print(arr1)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
arr2 = np.arange(20).reshape(5, 4)
print(arr2)
arr_transpose = arr2.T
print(arr_transpose)
arr_transpose = arr2.transpose()
print(arr_transpose)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


<h1 style="color:brown" align="center"> <b>Numpy - Numeric Python </b></h1>

**NumPy** is an extennsion to the Python programming language, adding support for large, multi-dimensional (numerical) arrays and matrics, along with a large library of high-level mathematical functions to operate on those arrays. The full form of NumPy is Numeric Python.

In [25]:
matrix = np.arange(10, dtype = float).reshape((2, 5))
print(matrix)
print("Stored in the C-style order (Row major):")
cmatrix = matrix.copy(order = 'C')
print(cmatrix)
for item in np.nditer(cmatrix):
    print(item, end = ", ")

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
Stored in the C-style order (Row major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 

In [26]:
matrix = np.arange(10, dtype = float).reshape((2, 5))
print(matrix)
print("Stored in the F-style order (Column major):")
fmatrix = matrix.copy(order = 'F')
print(fmatrix)
for item in np.nditer(fmatrix):
    print(item, end = ", ")

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
Stored in the F-style order (Column major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 5.0, 1.0, 6.0, 2.0, 7.0, 3.0, 8.0, 4.0, 9.0, 

In [27]:
matrix = np.arange(10, dtype = np.int8)
print(matrix, len(matrix))
matrix = np.append(matrix, [11, 22, 33, 44])
print(matrix, len(matrix))
matrix = np.insert(matrix, 3, [55, 66])
print(matrix, len(matrix))
matrix = np.delete(matrix, [5, 6, 8]) # index numbers
print(matrix)

[0 1 2 3 4 5 6 7 8 9] 10
[ 0  1  2  3  4  5  6  7  8  9 11 22 33 44] 14
[ 0  1  2 55 66  3  4  5  6  7  8  9 11 22 33 44] 16
[ 0  1  2 55 66  5  7  8  9 11 22 33 44]


In [28]:
matrix = np.array([22, 44, 77, 11, 88, 66])
print(matrix)
matrix1 = np.sort(matrix)  # ascending order
print(matrix1)
matrix1 = -np.sort(-matrix) # descending order
print(matrix1)

[22 44 77 11 88 66]
[11 22 44 66 77 88]
[88 77 66 44 22 11]


In [29]:
matrix1 = np.array([[11, 22], [33, 44]])
print(matrix1, matrix1.shape, matrix1.ndim)
matrix2 = np.array([[55, 66], [77, 88]])
print(matrix2, matrix2.shape, matrix2.ndim)
# joining these two matrices along axis = 0
matrix3 = np.concatenate((matrix1, matrix2))
print(matrix3, matrix3.shape, matrix3.ndim)
# joining these two matrices along axis = 1
matrix4 = np.concatenate((matrix1, matrix2), axis = 1)
print(matrix4, matrix4.shape, matrix4.ndim)

[[11 22]
 [33 44]] (2, 2) 2
[[55 66]
 [77 88]] (2, 2) 2
[[11 22]
 [33 44]
 [55 66]
 [77 88]] (4, 2) 2
[[11 22 55 66]
 [33 44 77 88]] (2, 4) 2


In [30]:
print("Stack the two arrays along axis 0")
matrix3 = np.stack((matrix1, matrix2))
print(matrix3, matrix3.shape, matrix3.ndim)
matrix4 = np.stack((matrix1, matrix2), axis = 1)
print(matrix4, matrix4.shape, matrix4.ndim)

Stack the two arrays along axis 0
[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]] (2, 2, 2) 3
[[[11 22]
  [55 66]]

 [[33 44]
  [77 88]]] (2, 2, 2) 3


In [31]:
arr1 = np.arange(10)
print(arr1)
print(arr1[0], arr1[5]) # indexing
print(arr1[3:7])        # slicing

[0 1 2 3 4 5 6 7 8 9]
0 5
[3 4 5 6]


In [32]:
arr2 = np.arange(20).reshape(4, 5)
print(arr2)
print(arr2[2, :])
print(arr2[:, 2])
print(arr2[1:3, 2:4])
print(arr2[1:, 2:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10 11 12 13 14]
[ 2  7 12 17]
[[ 7  8]
 [12 13]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [33]:
print(arr2)
print(arr2[0::2])
print(arr2[0::2, 1::2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[ 1  3]
 [11 13]]


In [34]:
arr1 = np.arange(10)
print(arr1, type(arr1))
print(arr1[2:5])
arr1[2:5] = 100
print(arr1)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[2 3 4]
[  0   1 100 100 100   5   6   7   8   9]


In [35]:
arr1 = np.arange(10)
print(arr1, type(arr1))
arr_view = arr1[2:5]  # creating a view
print(arr_view)
arr1[2:5] = 100
print(arr1)
print(arr_view)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[2 3 4]
[  0   1 100 100 100   5   6   7   8   9]
[100 100 100]


In [36]:
arr1 = np.arange(10)
print(arr1, type(arr1))
arr_copy = arr1[2:5].copy()  # creating a copy
print(arr_copy)
arr_copy[:] = 100
print(arr1)
print(arr_copy)
print(arr1[::-1])

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[100 100 100]
[9 8 7 6 5 4 3 2 1 0]


In [37]:
mystr = "university"
print(mystr, mystr[::-1])

university ytisrevinu


In [38]:
arr2 = np.zeros((6, 6))
arr2[[0, -1], :] = 1
arr2[:, [0, -1]] = 1
arr2

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [39]:
arr2 = np.zeros((6, 6))
arr2[[0, -1], :] = 1
arr2

array([[1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
arr1 = np.array([100, 20, -33, 44, 90, 35, -22])
print(arr1)
print(arr1 < 0)  # returns a boolean nd-array
print(arr1[arr1 < 0])
print(~(arr1 < 0))
print(arr1[~(arr1 < 0)])

[100  20 -33  44  90  35 -22]
[False False  True False False False  True]
[-33 -22]
[ True  True False  True  True  True False]
[100  20  44  90  35]


In [41]:
arr1 = np.array([100, 20, -33, 44, 90, 35, -22])
print(arr1)
print(arr1 % 2 == True)
print(arr1[arr1 % 2 == 0])  # retrieving even numbers
print(arr1[~(arr1 % 2 == 0)]) # retrieving odd numbers

[100  20 -33  44  90  35 -22]
[False False  True False False  True False]
[100  20  44  90 -22]
[-33  35]


In [42]:
arr1 = np.array([100, 20, -33, 44, 90, 35, -22])
print(arr1)
print((arr1 >= 20) & (arr1 <= 50))
print(arr1[(arr1 >= 20) & (arr1 <= 50)])
print(np.__version__)
print(arr1.nbytes)

[100  20 -33  44  90  35 -22]
[False  True False  True False  True False]
[20 44 35]
2.3.2
56


In [43]:
arr1 = np.array(['bob','pat','tom','bob','jim','john'])
print(arr1 == 'BOB')
print(arr1 == 'bob')
print(arr1[arr1 != 'bob'])
arr1[arr1 == 'bob'] = 'tim'
print(arr1)

[False False False False False False]
[ True False False  True False False]
['pat' 'tom' 'jim' 'john']
['tim' 'pat' 'tom' 'tim' 'jim' 'john']


In [44]:
nums = np.arange(6)
nums_sqrt = np.sqrt(nums)
print(nums_sqrt)
print(np.round(nums_sqrt,1), np.round(nums_sqrt, 4))
print(np.ceil(nums_sqrt))
print(np.floor(nums_sqrt))

[0.         1.         1.41421356 1.73205081 2.         2.23606798]
[0.  1.  1.4 1.7 2.  2.2] [0.     1.     1.4142 1.7321 2.     2.2361]
[0. 1. 2. 2. 2. 3.]
[0. 1. 1. 1. 2. 2.]


In [45]:
# dealing with random numbers
nums = np.random.randn(10)
print(nums)
print(np.average(nums), np.std(nums))

[ 0.06151301  0.07698787  0.55558586 -2.23071584 -1.66951652 -0.25410619
  0.89954834  0.21893039 -0.75764457  1.28502679]
-0.1814390853565984 1.0440100878605167


In [46]:
nums = np.random.randn(500000)
print(nums[:10])
print(np.average(nums), np.std(nums))

[ 0.07552923  0.24664122 -0.63464044  0.21989333 -0.04627843 -2.17766901
 -1.11731968  0.01537892  0.81099737 -2.33097613]
-0.00027537374768788836 0.9986526219111995


In [47]:
np.random.seed(10)
print(np.random.randn(10))

[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556
  0.26551159  0.10854853  0.00429143 -0.17460021]


In [48]:
print(np.random.randint(0, 5, 20))

[3 2 1 0 4 1 3 3 1 4 1 4 1 1 4 3 2 0 3 4]


In [49]:
pt1 = np.random.randn(10)
pt2 = np.random.randn(10)
e_dist = 0
for i in range(len(pt1)):
    e_dist += (pt1[i] - pt2[i]) ** 2
print(e_dist ** 0.5)
print(np.sqrt(np.sum((pt1 - pt2) ** 2)))
print(np.sqrt(np.sum(pow(np.subtract(pt1, pt2), 2))))

3.8306448080185502
3.8306448080185502
3.8306448080185502


In [50]:
a1 = np.array([[  0,  0,  0],
               [ 10, 10, 10],
               [ 20, 20, 20],
               [ 30, 30, 30]])
a2 = np.array([[0],[10],[20],[30]])
b1 = np.array([[  0,  1,  2],
               [  0,  1,  2],
               [  0,  1,  2],
               [  0,  1,  2]])
b2 = np.array([0, 1, 2])
print(a1, a1.shape)
print(a2, a2.shape)
print(b1, b1.shape)
print(b2, b2.shape)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] (4, 3)
[[ 0]
 [10]
 [20]
 [30]] (4, 1)
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]] (4, 3)
[0 1 2] (3,)


In [51]:
print(a1 + b1)
print(a1 + b2)
print(a2 + b1)
print(a2 + b2)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [52]:
print(np.add(a1, b1))
print(np.add(a1, b2))
print(np.add(a2, b1))
print(np.add(a2, b2))

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
